#!/usr/bin/zsh

sxhkd &
pidof bspswallow || bspswallow &
bspc rule -r "*"

bspc monitor HDMI-1-1 -d 1 2 3 4 5  
bspc monitor -d 6 7 8 9 10

bspc config normal_border_color "#5e81ac"
bspc config focused_border_color "#5e81ac"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          25

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a * floating=on

$HOME/.config/polybar/launch.sh &
xrandr --output HDMI-1-1 --mode 1920x1080 --primary --left-of eDP-1-1

feh --bg-fill ~/Pictures/walls/fr_light_nord.png
