#!/usr/bin/zsh

sxhkd &
pidof bspswallow || bspswallow &
bspc rule -r "*"

mainmonitor="$(bspc query --monitors --names | grep -v eDP-1-1 | head -n 1)"

if ! echo "$mainmonitor" | grep eDP-1-1 >/dev/null 2>&1; then
	xrandr --output "$mainmonitor" --mode 1920x1080 --primary --left-of eDP-1-1
	bspc monitor "$mainmonitor" -d 1 2 3 4 5
	bspc monitor eDP-1-1 -d 6 7 8 9 10
else
	bspc monitor -d 1 2 3 4 5
fi



bspc config normal_border_color "#5e81ac"
bspc config focused_border_color "#5e81ac"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          25

bspc rule -a mpv state=floating 
bspc rule -a Zathura state=tiled
bspc rule -a brave-browser state=floating

$HOME/.config/polybar/launch.sh &

feh --bg-fill ~/Pictures/walls/fr_light_nord.png
